language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
    - sys-img-armeabi-v7a-android-19
before_script:
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    - ./gradlew squidb-tests:installDebug squidb-tests:installDebugAndroidTest
script:
    - adb shell am instrument -w com.yahoo.squidb.test.test/android.test.InstrumentationTestRunner
